import Head from "next/head";
import Navbar from "../components/Navbar";
import Banner from "../components/Banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shoppers | Live Better</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/smallLogo.ico" />
      </Head>
      <main className="bg-lightBlue">
        <Navbar />
        <div className="max-w-contentContainer mx-auto bg-white">
          <Banner />
        </div>
      </main>
    </>
  );
}
