import Head from "next/head";
import Navbar from "../components/Navbar";
import Banner from "../components/Banner";
import { Product } from "../type";
import Products from "../components/Products";
import Footer from "../components/Footer";
import TopFooter from "../components/TopFooter";

interface Props {
  productData: Product;
}

export default function Home({ productData }: Props) {
  return (
    <>
      <Head>
        <title>Shoppers | Live Better</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/smallLogo.ico" />
      </Head>
      <main className="bg-lightBlue">
        <div className="max-w-contentContainer mx-auto bg-white">
          <Banner />
          <Products productData={productData} />
        </div>
      </main>
    </>
  );
}

//=============== SSR data fetching START here =============
export const getServerSideProps = async () => {
  const productData = await (
    await fetch("http://localhost:3000/api/productdata")
  ).json();

  return {
    props: { productData },
  };
};
//=============== SSR data fetching END here =============
